### ISSUE TITLE
ArrayIndexOutOfBoundsException and NullPointerException during processing large size data

### ISSUE THREAD

**Issue by lazykyama** [yahoojapan/yosegi-spark#6]
I've encountered two errors (`ArrayIndexOutOfBoundsException` and `NullPointerException`) during large size data.

The former error might be resolved by applying the following change. As far as I investigated it, looks like an uninitialized mapping information (`idxVector`) might be reused. But, need to confirm if this change is appropriate or not.

```diff
diff --git a/src/main/java/jp/co/yahoo/yosegi/spark/inmemory/SparkDoubleMemoryAllocator.java b/src/main/java/jp/co/yahoo/yosegi/spark/inmemory/SparkDoubleMemoryAllocator.java
index 8396e5b..36d1118 100644
--- a/src/main/java/jp/co/yahoo/yosegi/spark/inmemory/SparkDoubleMemoryAllocator.java
+++ b/src/main/java/jp/co/yahoo/yosegi/spark/inmemory/SparkDoubleMemoryAllocator.java
@@ -186,6 +186,7 @@ public class SparkDoubleMemoryAllocator implements IMemoryAllocator{
   @Override
   public IDictionary createDictionary( final int size ) throws IOException {
     idxVector = vector.reserveDictionaryIds( vectorSize );
+    idxVector.putInts(0, vectorSize, 0);
     SparkDoubleDictionary dic = new SparkDoubleDictionary( size );
     vector.setDictionary( dic );
     return dic;
```

However, even if the above change is applied, the latter error (`NullPointerException`) still happens.

Note that this error never happen when exporting to Parquet format.

### Reproduction code

https://gist.github.com/lazykyama/6131cefefa127662c6751d1e8b92ed6e

### How to reproduce this issue

* Apply a patch described in #5 to latest code, and build jar
* Download 1 Year dataset from a link below, and decompress it
    - https://rapidsai.github.io/demos/datasets/mortgage-data
* Run a convert script in the above gist from original csv to Yosegi
    - `spark-submit --master local[*] --jars ./yosegi-spark/jars/yosegi/latest/yosegi.jar,./yosegi-spark/target/scala-2.12/yosegi-spark-v3-0-0_2.12-1.0.jar convert.py`
    - Please change paths to dataset and etc if needed.
* Run a test script in the above gist
    - For `ArrayIndexOutOfBoundsException`: `spark-submit --master local[*] --conf spark.executor.memory=16g --conf spark.driver.memory=16g --conf spark.driver.memoryOverhead=2g --conf spark.executor.memoryOverhead=2g --jars ./yosegi-spark/jars/yosegi/latest/yosegi.jar,./yosegi-spark/target/scala-2.12/yosegi-spark-v3-0-0_2.12-1.0.jar run.py --format yosegi > yosegi_outerr.log 2>&1`
    - For `NullPointerException`: `spark-submit --master local[*] --conf spark.executor.memory=16g --conf spark.driver.memory=16g --conf spark.driver.memoryOverhead=2g --conf spark.executor.memoryOverhead=2g --jars ./yosegi-spark/jars/yosegi/latest/yosegi.jar,./yosegi-spark/target/scala-2.12/yosegi-spark-v3-0-0_2.12-1.0.jar run.py --format yosegi --part > yosegi_part_outerr.log 2>&1`

### Stacktrace

Former error:

```
20/08/17 03:05:11 ERROR Executor: Exception in task 0.0 in stage 27.0 (TID 3698)
java.lang.ArrayIndexOutOfBoundsException: 1
        at jp.co.yahoo.yosegi.spark.inmemory.SparkDoubleMemoryAllocator$SparkDoubleDictionary.decodeToDouble(SparkDoubleMemoryAllocator.java:63)
        at org.apache.spark.sql.execution.vectorized.OnHeapColumnVector.getDouble(OnHeapColumnVector.java:460)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:155)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Latter error:

```
20/08/17 03:07:58 ERROR Executor: Exception in task 5.0 in stage 3.0 (TID 217)
java.lang.NullPointerException
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:132)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by koijima** [comment]
Thank you for reporting the bug.
I investigate the cause of the incorrect dictionary access and fix the code.

**Comment by koijima** [comment]
The Spark Vector has not been properly initialized.
In this [PR](https://github.com/yahoojapan/yosegi-spark/pull/8) we have fixed the initialization process. I think this will prevent access to unintended values.

If there is a problem, please reopen this problem.
Thanks for your cooperation!
